### ISSUE TITLE
Support for new Bitpanda Pro websocket api

### ISSUE THREAD

**Issue by pyranja** [nardew/cryptoxlib-aio#12]
Bitpanda Pro is adding a new websocket channel [`TRADING` for order updates](https://developers.bitpanda.com/exchange/#-strong-preview--strong---trading-channel) and the ability to [create/cancel orders](https://developers.bitpanda.com/exchange/#-strong-preview--strong---websocket-order-api).

**Comment by nardew** [comment]
As the documentation says:

> This is a preview. Events, payloads and channel behavior are subject to change.

To avoid potential double work due to API changes the new websockets will be scheduled when API is deemed stable.

**Comment by pyranja** [comment]
Would you be willing to provide feedback on the api preview?

**Comment by nardew** [comment]
I had a look and there is nothing that would stroke me. The only thing which sounds ambiguous to me is the following one for TRADING channel:

> Within a single websocket connection order updates of a single market are received...

First I understood that there can be only one market subscribed per one TRADING websocket which would require including market in the subscription message. Having thought about it again I realized you might want to say that consistency of each market is ensured only within one websocket and not among several websockets.

Just out of curiosity, is it expected that the new TRADING channel will be much more performant than the existing ACCOUNT UPDATES channel that duplicates some of the functionality? I found the existing channel rather swift when it comes to order updates.

**Comment by pyranja** [comment]
> I had a look and there is nothing that stroke me. The only thing which sounds ambiguous to me is the following one for TRADING channel:

Do you like it? :smirk_cat: 

> First I understood that there can be only one market subscribed per one TRADING websocket which would require including market in the subscription message. Having thought about it again I realized you might want to say that consistency of each market is ensured only within one websocket and not among several websockets.

We want to say that updates within one websocket connection are always in order as they happened and none is omitted. This is in contrast to many of our competitors, that cannot guarantee that.
When the websocket connection is lost and a client re-connects it might miss updates that happen while it was not connected of course.

> Just out of curiosity, is it expected that the new TRADING channel will be much more performant than the existing ACCOUNT UPDATES channel that duplicates some of the functionality? I found the existing channel rather swift when it comes to order updates.

Yes, we can see significantly improved (tail) latencies on these updates for HFT workloads, where clients have many open positions that change very often.
Another benefit we see is that the TRADING channel payloads are smaller, that might make it simpler to understand and integrate with.

**Comment by nardew** [comment]
> Do you like it? :smirk_cat: 

I think it is alright 😎 

Having dealt with several APIs (especially websockets) I must say that bitpanda is doing quite well in terms of functionality, friendliness and performance.

**Comment by pyranja** [comment]
fyi the websocket api updates are now out of preview and generally available https://developers.bitpanda.com/exchange/#subscription-channels

**Comment by nardew** [comment]
Thanks, I'll take a look when time permits.

**Comment by nardew** [comment]
Hi @pyranja, I just want to inform you that the Trading and Orders subscriptions have been implemented. So far they are in PR #27. In case you fancy giving it a try I will wait with the merge. If not, let me know and I merge it immediately.

I saw you guys have an own client at bitpanda, I like the code ;), well done!

**Comment by pyranja** [comment]
hi @nardew would it be ok for you if we list this library on https://developers.bitpanda.com/exchange as a 3rd party library?

The text would be: 

> <a href="https://github.com/nardew/cryptoxlib-aio" target="_blank">cryptoxlib-aio</a> is a compact Python library
    providing access to REST and WEBSOCKET API of selected crypto exchanges.

and there is a disclaimer that Bitpanda is not testing/verifying functionality of community libraries.

**Comment by nardew** [comment]
Sure, I will be glad! At least I will feel compelled to add missing rest calls I was postponing for quite some time. 😬

**Comment by nardew** [comment]
Issue #28 added as "a proof" 😀 (not that it proves anything...)

**Comment by nardew** [comment]
Hi @pyranja, missing REST API calls added via #28 and #29.

**Comment by pyranja** [comment]
@nardew the mention is now live in our docs https://developers.bitpanda.com/exchange/#community-libraries

Thanks for your good work on this client lib :+1:
