### ISSUE TITLE
Issue on Binance

### ISSUE THREAD

**Issue by gambitov** [nardew/cryptoxlib-aio#20]
I am trying to runthe example binance_ws.py but  I have an error, I remplazed API KEY for my API KEY and SEC (Here remplazed by XXX) but does not work. Any suggestion?

Datails of errors are below

Available loggers: ['concurrent.futures', 'concurrent', 'asyncio', 'aiohttp.access', 'aiohttp', 'aiohttp.client', 'aiohttp.internal', 'aiohttp.server', 'aiohttp.web', 'aiohttp.websocket', 'cryptoxlib.Timer', 'cryptoxlib', 'websockets.protocol', 'websockets', 'websockets.server', 'websockets.client', 'cryptoxlib.WebsocketMgr', 'cryptoxlib.CryptoXLibClient', 'cryptoxlib.PeriodicChecker', 'cryptoxlib.clients.bitforex.BitforexWebsocket', 'cryptoxlib.clients.bitforex', 'cryptoxlib.clients', 'cryptoxlib.clients.bitforex.BitforexClient', 'cryptoxlib.clients.liquid.LiquidWebsocket', 'cryptoxlib.clients.liquid', 'cryptoxlib.clients.liquid.LiquidClient', 'cryptoxlib.clients.bibox.BiboxWebsocket', 'cryptoxlib.clients.bibox', 'cryptoxlib.clients.bibox.BiboxClient', 'cryptoxlib.clients.bibox_europe.BiboxEuropeWebsocket', 'cryptoxlib.clients.bibox_europe', 'cryptoxlib.clients.bibox_europe.BiboxEuropeClient', 'cryptoxlib.clients.bitpanda.BitpandaWebsocket', 'cryptoxlib.clients.bitpanda', 'cryptoxlib.clients.bitpanda.BitpandaClient', 'cryptoxlib.clients.binance.BinanceWebsocket', 'cryptoxlib.clients.binance', 'cryptoxlib.clients.binance.BinanceClient', 'cryptoxlib.clients.bitvavo.BitvavoWebsocket', 'cryptoxlib.clients.bitvavo', 'cryptoxlib.clients.bitvavo.BitvavoClient', 'cryptoxlib.clients.btse.BtseWebsocket', 'cryptoxlib.clients.btse', 'cryptoxlib.clients.btse.BtseClient', 'cryptoxlib.clients.aax.AAXWebsocket', 'cryptoxlib.clients.aax', 'cryptoxlib.clients.aax.AAXClient']

Traceback (most recent call last):
  File "c:/Users/Gabriel/Desktop/Bot/BinanaceEx.py", line 56, in <module>
    asyncio.run(run())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:/Users/Gabriel/Desktop/Bot/BinanaceEx.py", line 33, in run
    api_key = os.environ['XXX']
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XXX'

**Comment by nardew** [comment]
I think you misunderstood usage of `os.environ['ENVIRONMENT_VARIABLE_NAME']`.

https://docs.python.org/3/library/os.html#os.environ

If your api key is stored in environment variable API_KEY_ENV, then you load it as

`api_key = os.environ['API_KEY_ENV']`

If you are not using environment variables, then simply assign your api key into the variable directly

`api_key ='<YOUR API KEY>'`

**Comment by nardew** [comment]
@gambitov was your issue resolved?

**Comment by gambitov** [comment]
Dear @nardew,

You are very kind to be aware of my issue, I try to set my API and SEC directly (api_key ='<MY API KEY>') but It doesn't work. I think I must have to study the code deeper. 

Examples are: binance_rest_api.py  and binance_ws.py, Do I need both at time or Could I use them independently ?. 

thank you for all your help

**Comment by nardew** [comment]
The two are independent, the first one is for REST API, the second one is for websockets. What's your error?

**Comment by nardew** [comment]
No follow up in ±2 months, issue closed.

**Comment by gambitov** [comment]
Oh, I'm sorry. I can't work with this library. Thank you.
