### ISSUE TITLE
Event loop is closed error?

### ISSUE THREAD

**Issue by Serpens66** [nardew/cryptoxlib-aio#21]
Trying to execute your examples (tried binance and bitpanda REST to print orderbook), but after the orderbook is printed, it also prints an error (using python 3.8 on windows):

```python
import asyncio
import logging
import os

from cryptoxlib.CryptoXLib import CryptoXLib
from cryptoxlib.clients.binance import enums
from cryptoxlib.Pair import Pair
from cryptoxlib.clients.binance.exceptions import BinanceException

LOG = logging.getLogger("cryptoxlib")
LOG.setLevel(logging.DEBUG)
LOG.addHandler(logging.StreamHandler())

async def run():
    api_key = ""
    sec_key = ""

    client = CryptoXLib.create_binance_client(api_key, sec_key)
    await client.get_orderbook(pair = Pair('ETH', 'BTC'), limit = enums.DepthLimit.L_5)
    
    await client.close() # error happens with and without this line.
    
if __name__ == "__main__":
    asyncio.run(run())
```

> > rest type [GET], resource [depth], params [{'symbol': 'ETHBTC', 'limit': '5'}], headers [{}], data [None]
<: status [200], response [{"lastUpdateId":1412346346,"bids":[["0.03061400","0.40500000"],["0.03061300","2.36500000"],["0.03061200","25.79300000"],["0.03061000","27.34100000"],["0.03060700","7.00000000"]],"asks":[["0.03061700","35.90500000"],["0.03061900","0.56500000"],["0.03062100","13.59100000"],["0.03062200","24.00000000"],["0.03062400","7.91600000"]]}]
Timer RestCall finished. Took 402.125 ms.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03BEDEC8>
Traceback (most recent call last):
  File "C:\Users\Serpens66\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Serpens66\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Serpens66\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\Serpens66\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by nardew** [comment]
Hi @Serpens66 , I have never tried it on windows with Python 3.8. If you are using virtual environments, could you try with python 3.7?

**Comment by Serpens66** [comment]
Will try it on Debian10 python 3.8 soon. Won't install virtual env or new python version on windows.

Is there a way to better debug this?
During my testing with asyncio I noticed that this kind of error is often a consequential error if somehting else throws an error within the event loop. So currently we do not see the reason for this in the traceback.

**Comment by nardew** [comment]
I tried Python 3.8 on macOS and did not face any issues apart from some deprecation warnings

**Comment by Serpens66** [comment]
Yes, it works fine on Debian10 Python 3.8.
So only windows might have problems with it. At windows I just write and test the code, the actual bot runs at Debian, so it is fine.
But still, maybe a note somewhere that it is not probperly tested on windows, might be good.
