### ISSUE TITLE
[Question] What is the reason for asyncio in webscocket?

### ISSUE THREAD

**Issue by Serpens66** [nardew/cryptoxlib-aio#22]
Hi :)

I'm new to asyncio in general, but I understood that for many simultan REST API calls, asyncio is much better than using threads, because asyncio makes use of the waiting time, while threads divide resources and most of the time just wait. And threads are limited in number, so you can't do 1000 REST calls at once for example.

But where is the advantage when using websocket? I mean where is the waiting time, asyncio is using for other tasks? You get a websocket message from the exchange and process them, after that you process the next message. There may be a small waiting time where you get no new message, but if this is the case, there is nothing else to do, so no need for asyncio.

Or is the whole point of asyncio+websocket that you can safe a single permanent thread? 
When you have a script for trading, which uses websocket, the websocket of course needs to run simultanously to your trading script... so is this the point where asyncio is used? If this is the case... I think threads or especially processes are superior to asyncio, for example just because my trading script has no waitingtime, it calculates nonstop..  Am I right?

**Comment by nardew** [comment]
Hi @Serpens66,

when you are using a single websocket, then indeed `asyncio` will not add any value. The advantage becomes apparent when you have multiple websockets opened at the same time. When one websocket performs IO heavy task (accesses filesystem, network, database, ...), other websockets can use this time to perform they job.

For your example with trading, the trading actions (buy, sell, ...) can be triggered by incoming websocket messages, you do not need to have a separate thread for the trading. But it will depend heavily on the design and way of trading.

Performance wise, asyncio may or not be superior to threads, it will all come down to a particular use case. I find its behaviour more predictable than threads and it helps avoid some pitfalls of concurrent programming (but introduces another ones of course 8-))
