### ISSUE TITLE
Candlesticks / klines support on websockets

### ISSUE THREAD

**Issue by ttamg** [nardew/cryptoxlib-aio#25]
I see that cryptoxlib-aio does not yet have support for subscribing to websockets candlesticks / klines / OHLC (choose your preferred name).  Certainly that is the case on Binance.  I don't know the other exchanges covered here so well.

Is this a design decision around candles, or perhaps has some complexities to deal with?  
... or just that no-one has wanted candlesticks on the WS feed yet?

Thanks for this great resource.

**Comment by nardew** [comment]
Hi @ttamg, there are no difficulties with implementing the binance candlestick stream, there was just no demand for it yet.

Can you confirm you are interested in this stream in particular? 

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams

If yes, I will add it in the upcoming days

**Comment by nardew** [comment]
Have a look at #26, it should address your request. If so, I will merge it.
