### ISSUE TITLE
Call for ticker_book

### ISSUE THREAD

**Issue by cyberjunky** [nardew/cryptoxlib-aio#41]
Do you also support ticker_book API calls?

I'm missing data like ask and bidprice in just price_ticker data.

Binance:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#symbol-order-book-ticker
Bitvavo:
https://docs.bitvavo.com/#tag/Market-Data/paths/~1ticker~1book/get

If OK I will add the Bitvavo call.

**Comment by nardew** [comment]
Hi,

for binance, it is available here: https://github.com/nardew/cryptoxlib-aio/blob/master/cryptoxlib/clients/binance/BinanceClient.py#L156

For bitvavo it is not present. If you can create a PR, it will be very much appreciated.

**Comment by cyberjunky** [comment]
@nardew done ;-)

https://github.com/nardew/cryptoxlib-aio/pull/43
https://github.com/nardew/cryptoxlib-aio/pull/42

**Comment by nardew** [comment]
Tip top, thanks. I will close the issue.

**Comment by nardew** [comment]
@cyberjunky version 3.9.0 available in PyPi
