### ISSUE TITLE
coin margain futures for Binance exchange

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#48]
is it possible to add coin margain futures for Binance exchange?

@davidmcnabnz @nardew

**Comment by nardew** [comment]
Hi @xiandong79 , it is in the pipe, though I cannot give you any precise estimate. Might be 3 weeks, might be 6 weeks...

**Comment by nardew** [comment]
@xiandong79 in #51 you can follow WIP, currently there are public market data endpoints for COIN-M futures.
