### ISSUE TITLE
Binanace Spot, Partial Book Depth Streams and others are missed in WS channel

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#49]
unlike cryptoxlib/clients/binance/BinanceFuturesWebsocket.py 

the cryptoxlib/clients/binance/BinanceWebsocket.py does not have  `Partial Book Depth Streams` and `Diff. Depth Stream` 

https://binance-docs.github.io/apidocs/spot/en/#diff-depth-stream

**Comment by nardew** [comment]
@xiandong79 implemented with #50
