### ISSUE TITLE
Running the client in background

### ISSUE THREAD

**Issue by bastienjalbert** [nardew/cryptoxlib-aio#52]
Hello,

I'm trying to use your websocket async client and I got problems to run asynchronously the client. 
I did something like :
```python
class Test(legacy.Legacy):
   def __init__(self, xx):
      self.client = CryptoXLib.create_aax_client(self.__api_key, self.__api_secret)

    async def account_update(self, response: dict) -> None:
        print(f"Callback account_update: [{response}]")

    async func(self):
        self.ws_request_client.compose_subscriptions([
            AccountSubscription(callbacks=[self.account_update])
        ])
        await self.ws_request_client.start_websockets())
        # a lot of other stuff then
        toto()
        tata() # do some orders on market
        .....
```

If I do that, await will block the execution flow and `toto`/`tata` will never be executed. However I'll see orders with `account_update` function callback (order that I do manually).
I would like to subscribe to Account but keep the execution flow, to execute `toto` and `tata`. I did tried this, but now I don't see orders (like websockets never been started) : 
```python
class Test(legacy.Legacy):
   def __init__(self, xx):
      self.client = CryptoXLib.create_aax_client(self.__api_key, self.__api_secret)

    async def account_update(self, response: dict) -> None:
        print(f"Callback account_update: [{response}]")

    async func(self):
        self.ws_request_client.compose_subscriptions([
            AccountSubscription(callbacks=[self.account_update])
        ])
        loop = asyncio.get_event_loop()
        loop.create_task(coro=self.ws_request_client.start_websockets())
        # a lot of other stuff then
        toto() # now executed
        tata() # now executed, do some orders on market
        .....
```
I'm calling the function `func` in another class with `asyncio.run(func())` to avoid the await/async all my app.
Any advise would be appreciated

**Comment by nardew** [comment]
Hi @bastienjalbert ,
you are probably after a construct like this:

```python
async def main_loop():
    while True:
        toto()
        tada()
        await asyncio.sleep(1) # sleep asynchornously for 1 sec

async def run():
    client = CryptoXLib.create_aax_client(api_key, sec_key)
    client.compose_subscriptions(...)

        await asyncio.gather(*[
            client.start_websockets(),
            main_loop()
        ])

    await client.close()

if __name__ == "__main__":
    async_run(run())
```

Have a look at `examples/ws_subscriptions.py`.

**Comment by bastienjalbert** [comment]
Thank you @nardew, appreciate that !

Is there any way to prevent main_loop() to be executed (like waitFor) until the `client.start_websockets()` has been "launched" ? 
Since `toto()` or `tada()` may push orders on the market, I would like to monitoring them through the `compose_subscriptions` callback, but the websockets subscription / start looks slower then my `main_loop()`

**Comment by nardew** [comment]
I am not quite sure what is the ultimate goal but if you need to make sure toto and tada are called only after the streams are initiated, then you can

i) add toto and tada directly into the websocket callback
i) have a variable which is set in the websocket callback and then have a check for the variable in the main loop

**Comment by nardew** [comment]
Since there was not follow up in the past month, I am closing the thread. Re-open if needed.
