### ISSUE TITLE
create_margin_order() returns "code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."

### ISSUE THREAD

**Issue by alaaedeen** [nardew/cryptoxlib-aio#54]
create margin order always returns code 1102: "A mandatory parameter was not sent, was empty/null, or malformed.", but does not specify which parameter is malformed.

the following parameters are passed to the function and everything seems to check out: 
{'symbol': 'BTCUSDT', 'side': 'BUY', 'type': 'LIMIT', 'quantity': '0.007715', 'quoteOrderQty': None, 'price': '28462.699999999997', 'stopPrice': None, 'isIsolated': 'TRUE', 'newClientOrderId': None, 'icebergQty': None, 'recvWindow': None, 'timestamp': 1621691008642}

**Comment by alaaedeen** [comment]
Seems like time_in_force is a required parameter, however API suggests it is optional. only when TImeInForce is used does  create_margin_order() successfully place the order

**Comment by nardew** [comment]
Hi @alaaedeen , thanks for spotting this. Fixed in #55
