### ISSUE TITLE
Kraken exchange wrapper

### ISSUE THREAD

**Issue by svyatoslavkravchneko** [nardew/cryptoxlib-aio#67]
Make sense to add this exchange to repository.
What you think guys?

**Comment by nardew** [comment]
Hi @svyatoslavkravchneko, I definitely agree it would be nice to have Kraken as an addition but unfortunately due to time constraints this cannot be worked on in the near future, unless there is a huge demand for it which is apparently not happening.

**Comment by svyatoslavkravchneko** [comment]
@nardew 
We are writing, something similar on Celery.
Executing service on Celery for crypto exchanges
When it will be ready, we can communicate, as your feedback will be nice to hear

**Comment by nkrsic** [comment]
> @nardew
> We are writing, something similar on Celery.
> Executing service on Celery for crypto exchanges
> When it will be ready, we can communicate, as your feedback will be nice to hear

Interesting.
