### ISSUE TITLE
Binance listenkeyExpired in BinanceFuture Websocket Channel

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#68]
```
I [2021-07-01 10:30:49,174] [.swap_account_update] swap_account_update: {'stream': '6uxymh85KEkkHQJFqQeUeWjY5eCQO00G5s0DZx3aQtZ9Nn6IcGqxGGRWBKzr6SVx', 'data': {'e': 'listenKeyExpired', 'E': 1625135449173}} 
I [2021-07-01 10:30:49,175] [.swap_account_update] swap_account_update: {'stream': '6uxymh85KEkkHQJFqQeUeWjY5eCQO00G5s0DZx3aQtZ9Nn6IcGqxGGRWBKzr6SVx', 'data': {'e': 'listenKeyExpired', 'E': 1625135449173}} 
```

after  **exact 1 hour run**, this error this happens.

Extra actions on this is needed, like when receive a msg like above, the client do `get_listenkey()` + `the re-connection()` +  `send_subscription_message()` directly and update internal listenkey.

**Comment by xiandong79** [comment]
in `_process_message()` in `cryptoxlib/clients/binance/BinanceCommonWebsocket.py` file

**Comment by xiandong79** [comment]
also, in my log file, I do not find a line like

```
            LOG.info(f"[{self.id}] Refreshing listen key.")
```
maybe this logic does work in running

**Comment by xiandong79** [comment]
for now, I have to restart directly in strategy , which is not a good idea

```
        if response.get('data').get('e') == 'listenKeyExpired':
            self.account_compose_subscriptions()
```

```
    def account_compose_subscriptions(self):
        # Bundle another subscriptions into a separate websocket
        self.swap_client.compose_subscriptions([SwapAccountSubscription(callbacks=[self.swap_account_update])])
        ])
```

**Comment by nardew** [comment]
@xiandong79 are you sure you are running with the latest version? Can you run cryptoxlib in debug and see if in 30 minutes the listen key gets refreshed? I am not facing this issue anymore.

**Comment by nardew** [comment]
@xiandong79 Are you sure you are running the latest cryptoxlib 5.1.5? I do not face the issue.
