### ISSUE TITLE
aiohttp==3.7.4 is compatiable with python3.10

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#79]
please loose the aiohttp version

**Comment by nardew** [comment]
Hi @xiandong79 , which version are you after?

**Comment by xiandong79** [comment]
I use the latest aiohttp.

I suggest to change this line to 
```
aiohttp>=3.7.4
```

**Comment by nardew** [comment]
@xiandong79 I ran several tests with python 3.10 and aiohttp 3.7.4 works perfectly fine. What exactly is your error?
